# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9459b51caa68e81ab9231b07065bc8826fadb16245b2a52287f1929c1cb2c53a112503f008d6fc5dc64638eea9cd0c73dea52d009461242503f0b8924feb4a7d

test:
  secret_key_base: cbe27e882a97ba5ebe46759a805c41f703fffb45dd655e3ceb89ec6e9caf4ea8f4771aebe8f1b73975e55ea9d8834f12f3c440845858c4c0c31dded78d08d5f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
